In [1]:
import glob
files = glob.glob("C:/Code/data/ronen/*.mpg")
files

['C:/Code/data/ronen\\FM normal1.mpg',
 'C:/Code/data/ronen\\preterm cramps.mpg',
 'C:/Code/data/ronen\\preterm normal.mpg',
 'C:/Code/data/ronen\\preterm poor.mpg']

In [2]:
%%time

import cv2
import numpy as np
import pickle

for file in files:

    cap = cv2.VideoCapture(file)

    ret, frame1 = cap.read()
    prvs = cv2.cvtColor(frame1,cv2.COLOR_BGR2GRAY)
    hsv = np.zeros_like(frame1)
    hsv[...,1] = 255

    mags = []
    angs = []

    while(cap.isOpened()):
        ret, frame2 = cap.read()
        if ret == False:
            break

        next = cv2.cvtColor(frame2,cv2.COLOR_BGR2GRAY)


        flow = cv2.calcOpticalFlowFarneback(prvs,next, None, 0.5, 3, 15, 3, 5, 1.2, 0)

        mag, ang = cv2.cartToPolar(flow[...,0], flow[...,1])

        mags.append(mag)
        angs.append(ang)
    
#     hsv[...,0] = ang*180/np.pi/2
#     hsv[...,2] = cv2.normalize(mag,None,0,255,cv2.NORM_MINMAX)
#     rgb = cv2.cvtColor(hsv,cv2.COLOR_HSV2BGR)

#     cv2.imshow('frame2',rgb)
#     k = cv2.waitKey(1) & 0xff
#     if k == 27:
#         break
#     elif k == ord('s'):
#         cv2.imwrite('opticalfb.png',frame2)
#         cv2.imwrite('opticalhsv.png',rgb)
        prvs = next
    
    cap.release()
    cv2.destroyAllWindows()
    
    
    output = open(f"{file}.data.pkl", 'wb')
    pickle.dump(mags, output)
    output.close()

MemoryError: 

In [78]:
dxdy = []
for m,a in enumerate(zip(mags,angs)):
    dx=m*np.cos(a)
    dy=m*np.sin(a)
    dy=dy.round().astype('int8')
    dx=dx.round().astype('int8')
    dxdy.append()

In [64]:
print(len(mags))
print(len(mags[0]))
print(len(mags[0][0]))
mags[0][0][0]

1008
576
720


0.0

In [34]:
my_mags = np.array(mags)
print(my_mags.shape)

my_mags[0,:,:].max()

(1008, 576, 720)


14.688688

In [36]:
# all_max = [my_mags[i,:,:].max() for i in range(my_mags.shape[0])]
# all_max

[14.688688,
 13.739795,
 16.085958,
 14.240208,
 10.018895,
 15.862837,
 15.630105,
 17.051067,
 15.41973,
 14.070647,
 14.22913,
 16.389988,
 11.841466,
 15.272616,
 17.384924,
 30.158197,
 33.337589,
 37.858574,
 40.83675,
 34.148094,
 35.720764,
 43.21117,
 51.272327,
 24.147028,
 22.493149,
 10.612891,
 17.243078,
 45.968678,
 33.24976,
 18.583838,
 7.9330745,
 15.83896,
 11.449791,
 13.516243,
 10.752151,
 10.300423,
 11.597555,
 9.2235098,
 17.52948,
 22.702999,
 19.940195,
 19.109972,
 16.572212,
 22.742607,
 22.704855,
 31.463383,
 29.360065,
 21.963888,
 22.139536,
 15.53243,
 21.599701,
 20.486322,
 30.239922,
 20.046532,
 24.261295,
 31.341311,
 25.296591,
 13.331162,
 19.35269,
 19.99634,
 32.948078,
 30.450804,
 23.758814,
 19.605362,
 15.565074,
 12.492922,
 13.087082,
 10.901459,
 9.7840147,
 17.171928,
 13.438189,
 16.706841,
 19.997602,
 21.804708,
 19.34906,
 12.918831,
 17.021914,
 20.958134,
 32.848331,
 27.901716,
 23.293922,
 30.337122,
 13.321982,
 23.136395,
 21

In [53]:
my_mags

array([[[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       ..., 
       [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0., 

In [47]:
my_mags.dtype

dtype('float32')

In [52]:
import pickle

output = open('C:/Code/data/ronen/data.pkl', 'wb')
pickle.dump(my_mags, output, -1)
output.close()

In [37]:
import pandas as pd

pd.DataFrame(all_max)

0
0     14.688688
1     13.739795
2     16.085958
3     14.240208
4     10.018895
5     15.862837
6     15.630105
7     17.051067
8     15.419730
9     14.070647
10    14.229130
11    16.389988
12    11.841466
13    15.272616
14    17.384924
15    30.158197
16    33.337589
17    37.858574
18    40.836750
19    34.148094
20    35.720764
21    43.211170
22    51.272327
23    24.147028
24    22.493149
25    10.612891
26    17.243078
27    45.968678
28    33.249760
29    18.583838
...         ...
978   17.165564
979   12.244277
980    9.648597
981    8.583302
982    9.590098
983    8.789003
984   10.294528
985    8.735118
986   13.587940
987    6.848715
988    7.663174
989    8.155581
990    9.278575
991    9.151305
992    9.195323
993    7.933350
994    6.809147
995    9.248010
996    8.571018
997   11.110141
998    7.001009
999   10.080682
1000   9.027456
1001   9.690022
1002  17.614769
1003   8.356709
1004   8.415121
1005   8.590186
1006   9.735466
1007   9.259565

[1008 rows x 1 columns]

In [32]:
import matplotlib.pyplot as plt
%matplotlib notebook


C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\axes\_axes.py:6097: UserWarning: 2D hist input should be nsamples x nvariables;
 this looks transposed (shape is 576 x 720)
  '(shape is %d x %d)' % inp.shape[::-1])


([array([ 576.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.]),
  array([ 576.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.]),
  array([ 576.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.]),
  array([ 576.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.]),
  array([ 576.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.]),
  array([ 576.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.]),
  array([ 576.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.]),
  array([ 576.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.]),
  array([ 576.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.]),
  array([ 576.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.]),
  array([ 576.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.]),
  array([ 576.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.]),
  array([ 576.,    0.,    0.

In [1]:
import numpy as np
import cv2

cap = cv2.VideoCapture("C:/Code/data/ronen/term cramps (2).mpg")

# params for ShiTomasi corner detection
feature_params = dict( maxCorners = 100,
                       qualityLevel = 0.3,
                       minDistance = 7,
                       blockSize = 7 )

# Parameters for lucas kanade optical flow
lk_params = dict( winSize  = (15,15),
                  maxLevel = 2,
                  criteria = (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 10, 0.03))

# Create some random colors
color = np.random.randint(0,255,(100,3))

# Take first frame and find corners in it
ret, old_frame = cap.read()
old_gray = cv2.cvtColor(old_frame, cv2.COLOR_BGR2GRAY)
p0 = cv2.goodFeaturesToTrack(old_gray, mask = None, **feature_params)

# Create a mask image for drawing purposes
mask = np.zeros_like(old_frame)

while(1):
    ret,frame = cap.read()
    frame_gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # calculate optical flow
    p1, st, err = cv2.calcOpticalFlowPyrLK(old_gray, frame_gray, p0, None, **lk_params)

    # Select good points
    good_new = p1[st==1]
    good_old = p0[st==1]

    # draw the tracks
    for i,(new,old) in enumerate(zip(good_new,good_old)):
        a,b = new.ravel()
        c,d = old.ravel()
        mask = cv2.line(mask, (a,b),(c,d), color[i].tolist(), 2)
        frame = cv2.circle(frame,(a,b),5,color[i].tolist(),-1)
    img = cv2.add(frame,mask)

    cv2.imshow('frame',img)
    k = cv2.waitKey(30) & 0xff
    if k == 27:
        break

    # Now update the previous frame and previous points
    old_gray = frame_gray.copy()
    p0 = good_new.reshape(-1,1,2)

cv2.destroyAllWindows()
cap.release()

KeyboardInterrupt: 

In [4]:
import glob
files = glob.glob("C:/Code/data/ready/*.pkl")
files

['C:/Code/data/ready\\FM normal1.mpg.data.pkl',
 'C:/Code/data/ready\\preterm cramps.mpg.data.pkl',
 'C:/Code/data/ready\\term cramps (2).mpg.data.pkl']

In [7]:
import pickle

file = open(files[0], mode='rb')
pic1 = pickle.load(file)
file.close()

In [9]:
%%time

pic_1_arr = np.array(pic1)


Wall time: 1.21 s


In [11]:
%whos

Variable    Type              Data/Info
---------------------------------------
ang         ndarray           576x720: 414720 elems, type `float32`, 1658880 bytes (1.58203125 Mb)
angs        list              n=1811
cap         VideoCapture      <VideoCapture 0000021051094690>
cv2         module            <module 'cv2.cv2' from 'C<...>\cv2.cp36-win_amd64.pyd'>
file        BufferedReader    <_io.BufferedReader name=<...>FM normal1.mpg.data.pkl'>
files       list              n=3
flow        ndarray           576x720x2: 829440 elems, type `float32`, 3317760 bytes (3.1640625 Mb)
frame1      ndarray           576x720x3: 1244160 elems, type `uint8`, 1244160 bytes (1.1865234375 Mb)
frame2      NoneType          None
glob        module            <module 'glob' from 'C:\\<...>Anaconda3\\lib\\glob.py'>
hsv         ndarray           576x720x3: 1244160 elems, type `uint8`, 1244160 bytes (1.1865234375 Mb)
mag         ndarray           576x720: 414720 elems, type `float32`, 1658880 bytes (1.58203

In [15]:
print(pic_1_arr.shape)

(1057, 576, 720)
